### ISSUE TITLE
Hi, do you mind open sourcing this project?

### ISSUE THREAD

**Issue by hackthehackerman** [crossle/KitKatEmoji#2]
Hello Crossle, sorry I have to open an issue because I couldn't find any other way to contact you. I am wondering if you would open source this project so I can add it into my android application? Or if that's too much trouble, may I have your permission to use your project in my application?

Thanks!

**Comment by crossle** [comment]
* [x] Completed task
* [ ] Unfinished task
    * [x] Nested task
