### ISSUE TITLE
Issue with including the library

### ISSUE THREAD

**Issue by tommytcchan** [crossle/KitKatEmoji#4]
Included it in build.gradle, but am seeing this issue. Tried to added tools ns and the tools:replace declaration but to no avail

Error:(64, 7) Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@icon value=(@drawable/burner_icon) from AndroidManifest.xml:64:7
  	is also present at com.github.crossle:KitKatEmoji:v1.0.0:13:9 value=(@drawable/ic_launcher)
  	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:59:3 to override

**Comment by tommytcchan** [comment]
Pull request opened to remove the declaration:

https://github.com/crossle/KitKatEmoji/pull/3

**Comment by crossle** [comment]
OK, thanks
