### ISSUE TITLE
请问如何在TextView显示表情？

### ISSUE THREAD

**Issue by 06peng** [crossle/KitKatEmoji#5]
Hello，如何把ios版的表情转化成KitkatEmoji并显示在TextView呢？好像数据结构并不相同。但是ios可以成功转换KitKatEmoji表情，求帮忙。谢谢
！--------------------------------------------------------------
已解决！

**Comment by crossle** [comment]
不太明白，你说的数据结构不同，表情都是些 unicode, 都是通用的

**Comment by 06peng** [comment]
非常感谢回复。需要就是聊天的时候，别人用ios发的表情我收到的时候也可以转化成kitkatemoji表情。
